---
- name: Create a file
  hosts: localhost
  tasks:
    - name: Ensure the file exists
      file:
        path: /k8config/kubeadm-config.yaml
        state: touch
        mode: '0777'
    - name: Create test file
      copy:
        dest: /k8config/kubeadm-config.yaml
        owner: azureuser
        group: azureuser
        content: |
          remove this line, ansible added!
          apiVersion: kubeadm.k8s.io/v1beta4
          kind: InitConfiguration
          nodeRegistration:
            criSocket: unix:///var/run/cri-dockerd.sock
