---
- name: Create a file, configure ansible
  hosts: localhost
  become: yes
  tasks:
    - name: Install Azure CLI using curl 
      ansible.builtin.shell: 
        cmd: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
    - name: Login to Azure using Managed Identity 
      ansible.builtin.shell: 
        cmd: az login --identity
