---
- name: Retrieve secrets from Azure Key Vault
  hosts: localhost
  become: yes
  tasks:
    - name: Get secret from Azure Key Vault
      ansible.builtin.set_fact:
        my_secret: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'ssh-private-key', vault_url='https://lockkeyvault.vault.azure.net/') }}"

    - name: Display the secret
      ansible.builtin.debug:
        msg: "The secret value is: {{ my_secret }}"
