---
- name: Create a file with specific content
  hosts: all
  become: no
  tasks:
    - name: Create a file with content
      copy:
        dest: /myfiles/azure_rm.yml
        content: |
          plugin: azure.azcollection.azure_rm
          auth_source: msi
          include_vm_resource_groups:
            - k8-devops-rg
          keyed_groups:
            - key: tags.application"
        mode: '0666'

- name: Run Ansible inventory command
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List inventory
      command: ansible-inventory -i myazure_rm.yml --list
      register: inventory_output

    - name: Display inventory output
      debug:
        var: inventory_output.stdout

- name: Retrieve SSH key from Azure Key Vault
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Get SSH key from Key Vault
      set_fact:
        ssh_key: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'ssh-private-key', vault_url='https://lockkeyvault.vault.azure.net/') }}"
